### PR TITLE
Make the log like something/module.py.function:123

### PR DESCRIPTION
**Pull request by nigelbabu**

### CODE REVIEW

**Comment by mykaul** [comment]
@loadtheaccumulator - can this be reviewed and if ACK'ed, merged?

**Comment by loadtheaccumulator** [comment]
I thought Nigel and I had discussed this offline, as I was looking at configurability with the Python3 port. I can push that in this version to get it in sooner than later. I'll close this one with comment.

**Comment by loadtheaccumulator** [comment]
I'm writing a configurable log format option to avoid breaking existing formatting. I had planned it in the Python3 port, but will go ahead and make it so in the current version.

**Comment by nigelbabu** [comment]
When is this expected to land? I'd like to remove a lot of the extraneous logging.

**Comment by loadtheaccumulator** [comment]
I’ll drop this in the current version next, but as proposed won’t eliminate log entries, but rather makes the log more verbose with the additional fields.

**Pull request closed without merging**
